all:
  children:
    harbor:
      hosts:
        harbor-vm:
          ansible_host: 192.168.100.40

    kubernetes_load_balancers:
      hosts:
        k8s-lb-01:
          ansible_host: 192.168.100.91
        k8s-lb-02:
          ansible_host: 192.168.100.92

    kubernetes_control_planes:
      hosts:
        k8s-cp-01:
          ansible_host: 192.168.100.101
        k8s-cp-02:
          ansible_host: 192.168.100.102
        k8s-cp-03:
          ansible_host: 192.168.100.103

    kubernetes_workers:
      hosts:
        k8s-worker-01:
          ansible_host: 192.168.100.111
        k8s-worker-02:
          ansible_host: 192.168.100.112
        k8s-worker-03:
          ansible_host: 192.168.100.113

    kubernetes_nodes:
      children:
        kubernetes_control_planes:
        kubernetes_workers:
    
    argocd_bootstrap:
      hosts:
        k8s-cp-01:
          ansible_host: 192.168.100.101
    
    vpn_gateways:
      hosts:
        vpn-gateway:
          ansible_host: 192.168.100.60